### ISSUE TITLE
`make bootstrap-client` fails (words/SQL issue?)

### ISSUE THREAD

**Issue by junebash** [pointfreeco/isowords#10]
Upon running `make bootstrap-client`, the console throws the following output:

```
  ⚠️  Checking for Git LFS...
  ✅ Git LFS is good to go!
touch Sources/AppAudioLibrary/Resources/empty.mp3
touch Sources/AppClipAudioLibrary/Resources/empty.mp3
/dev/stdin:173: INSERT failed: UNIQUE constraint failed: words.word
/dev/stdin:236: INSERT failed: UNIQUE constraint failed: words.word
/dev/stdin:629: INSERT failed: UNIQUE constraint failed: words.word
#...etc...
```

I've tried prepending sudo as well just in case, but no dice.

(p.s., thanks so much for open-sourcing this! It's a great service to the community.)

**Comment by stephencelis** [comment]
Haha, this and #9 are very timely 😄 Those are warnings that can be safely ignored. I'll update the Makefile to suppress those messages in the future.

**Comment by junebash** [comment]
Ha, what timing. 😆 Thanks!
