### ISSUE TITLE
make bootstrap-client does not fetch image assets

### ISSUE THREAD

**Issue by romero-ios** [pointfreeco/isowords#116]
**Describe the bug**
After cloning the repository, running:
`make bootstrap-client`
and then opening the workspace file and attempting to run the main `isowords` target produces the following error:
`The stickers icon set or app icon set named "AppIcon" did not have any applicable content.`

**To reproduce**
* Clone the repository
* Run `make bootstrap-client` in terminal
* Open workspace
* Run `isowords` target
* Build fails

**Expected behavior**
The app runs in the iOS simulator

**Screenshots/video**
<img width="2560" alt="Screen Shot 2021-06-11 at 4 05 40 PM" src="https://user-images.githubusercontent.com/8164778/121743214-ff494e00-cace-11eb-8a92-ef9c532d4779.png">

**Environment**
 - 2016 MacBook Pro 15":
 - OS: macOS 11.4

**Comment by mbrandonw** [comment]
Hi @romero-ios, did you follow all of the steps in the [Getting Started](https://github.com/pointfreeco/isowords#getting-started) instructions? In particular the first step that has you install git-lfs?

**Comment by romero-ios** [comment]
Hi @mbrandonw - yep, when I run the command the only output I see is:
```
 ⚠️  Checking for Git LFS...
 ✅ Git LFS is good to go!
```

**Comment by stephencelis** [comment]
@romero-ios Were you ever able to figure this out? I've done a fresh clone with no problem 😕

**Comment by VinceMikhailKearney** [comment]
@mbrandonw @stephencelis 
I am trying to set up the project as well, but `make bootstrap-client` isn't doing anything. I do have `git-lfs` installed. When trying to run any of the make commands separately as well, I also have no output. I am running an Apple Chip machine. Let me know if there is anything obvious I am missing please. 
I want to start a fresh project with TCA and would love to look at this project for some inspiration on modularisation etc.

**Comment by stephencelis** [comment]
@VinceMikhailKearney Can you post a screen shot or any console output you're seeing so we can have more info to debug? The project's schemes are shared, so they should show up.

**Comment by VinceMikhailKearney** [comment]
@stephencelis Thanks for such a quick response :)
Here is the screenshot of the terminal when I run `make bootstrap-client`
![Screenshot 2021-09-10 at 16 41 42](https://user-images.githubusercontent.com/22050106/132871739-66f0ad42-21ef-4f3b-8bd6-37930d6e6e5c.png)
And here is a screenshot of the Xcodeproject when I open it 😅 
![Screenshot 2021-09-10 at 16 42 00](https://user-images.githubusercontent.com/22050106/132871826-dce529a8-d734-42e8-94d9-8433ae1e61e9.png)

**Comment by stephencelis** [comment]
That looks like Xcode is opening the project as an SPM package and _not_ an Xcode project. Can you try closing that package and opening **App/isowords.xcodeproj** directly?

**Comment by VinceMikhailKearney** [comment]
Ah yes so it was 😅 I had been launching with `xed .` (force of habit) and hadn't even contemplated what was going wrong. I thought I had messed something up in the set up.
That is everything up and running now! Thanks very much @stephencelis!! Just after my meeting ended I'm on the go 👍🏻 
Now I've a fun game on the simulator for when I need a break 😬

**Comment by stephencelis** [comment]
@romero-ios I'm going to close this as it seems others are able to get things up and running OK. But if you have more info that can help us troubleshoot the issue, please let us know and we can re-open!

**Comment by rl-pavel** [comment]
Had a similar problem, but the issue seems to be that I installed `git-lfs` using Homebrew. Reinstalled manually and the project works as expected now 👍
