### ISSUE TITLE
Cube is incorrectly sized after rotation on iPad

### ISSUE THREAD

**Issue by chucks** [pointfreeco/isowords#126]
**Describe the bug**
If you rotate the iPad while playing isowords, the cube will not be sized the same as if the game was launched in that orientation.

**To reproduce**
- Launch isowords in landscape on iPad or the simulator
- start a new game
- rotate to portrait

- Launch isowords in portrait on iPad on the simulator
- start a new game
- rotate to landscape

**Expected behavior**
The cube would be shown without clipping and at the same size as if the app was launched in the given orientation.

**Screenshots/video**
![Launch Portrait](https://user-images.githubusercontent.com/544380/128236105-a59a2b98-8571-4d6b-a7b9-cfeb20e1876b.png)

![rotate to portrait](https://user-images.githubusercontent.com/544380/128236135-dc182997-74ea-4f88-a6a3-200772f11828.png)

![Launch Landscape](https://user-images.githubusercontent.com/544380/128236122-59d4cf57-d2e6-48a7-b3cb-6789c0ea9afd.png)

![rotate to landscape](https://user-images.githubusercontent.com/544380/128236155-69cc226b-e055-408d-9c63-79599ac92dbe.png)

**Environment**
- iPad running iOS 14.7.1

**Additional context**
Similar issues exist if you switch the iPad from full screen into side-by-side multitasking, but there are additional issues with the multitasking UI not covered by this problem. I'll log a separate issue for these.

**Comment by stephencelis** [comment]
Just merged your fix, thanks!
