### ISSUE TITLE
No file prompt when creating new files in the `isowords` local package

### ISSUE THREAD

**Issue by oronbz** [pointfreeco/isowords#149]
**Describe the bug**
When creating new swift file anywhere inside under the `isowords` local package, there's no file name prompt, and a new `File.swift` is instantly created instead. As opposed to creating new file outside the local pacakage, like inside the `AppClip` folder or `Config` folder. I've also noticed that I can't use any of my custom Xcode templates.

I've encountered this on my own projects as well and was wondering if you have a workaround for that, other than creating the file outside the local package and then dragging it inside.

**To reproduce**
1. `open App/isowords.xcodeproj`
2. Right click on the `BottomMenu` folder inside `isowords` ->  `Sources`.
3. Click `New File`
4. Choose `Swift File`
5. Click `Next`

**Expected behavior**
I expect a file name prompt:
![image](https://user-images.githubusercontent.com/1288090/167793799-a8fc6614-f3ba-40eb-ac63-56eaaded4009.png)

**Screenshots/video**
![image](https://user-images.githubusercontent.com/1288090/167793891-9ba31d9f-0c95-4bca-9f00-6bdb0ac9df18.png)

**Environment**
- Xcode Version 13.3.1 (13E500a)

**Comment by mbrandonw** [comment]
This is just how Xcode behaves. Files added to an SPM package skip the file name dialog, and files added to an app target do not. You should consider filing a Feedback with Apple.

I'm going to convert this to a discussion since it is not an issue with the project.
