### ISSUE TITLE
Change my user name?

### ISSUE THREAD

**Issue by Mozahler** [pointfreeco/isowords#19]
I tried asking via Twitter, but I think my privacy settings were messed up.
I was using the test version of isowords until you released it on the store, and then bought that version.
I notice a lot of people have normal user names, whereas mine is a randomly generated string. Can I change my user name?
If not, it's not a big deal... Alas, I'm afraid my days in the top ten are forever gone!

**Comment by stephencelis** [comment]
Hey @Mozahler! Your username is actually tied to Game Center. If you head over to Settings app you should be able to update it there.

**Comment by Mozahler** [comment]
🤦 never occurred to me! thanks.  appreciate all you guys do for the community.
