### ISSUE TITLE
Text truncation issues for onboarding screens with Accessibility text sizes

### ISSUE THREAD

**Issue by chucks** [pointfreeco/isowords#43]
Hi,

I realize this may have been improved with #8 , but just in case my issue is different I wanted to log it.

I have my phone set to the smallest of the "accessibility" dynamic type sizes, and there are a couple places in the onboarding flow where words are truncated.

![IMG_4797](https://user-images.githubusercontent.com/544380/112383027-fb254580-8cc2-11eb-919f-4a4f0b538473.PNG)
![IMG_4796](https://user-images.githubusercontent.com/544380/112383033-fe203600-8cc2-11eb-9904-fbd2c6f8af7e.PNG)

I'm super happy overall to see a game like this support Dynamic Type, since games are often difficult to play for low-vision users.

There are other places where text layout isn't always optimal, but they don't affect playability the way truncation does.

**Comment by stephencelis** [comment]
This should indeed be fixed by #8! Can you please reopen, though, if you find that to not be the case? We still don't support the extra-extra-extra-extra large text sizes in the accessibility section of settings, but are aware and will try to address that in the future.
