### ISSUE TITLE
Can't set a custom icon on iPad

### ISSUE THREAD

**Issue by chucks** [pointfreeco/isowords#78]
When you attempt to set a custom icon from Settings…Appearance on iPad, the first tap on a custom icon will select it, but nothing else will happen. If you tap again, you'll see a confirmation from the system, but the stock icon will be in the dialog box, and the actual icon on device will not be changed.

https://user-images.githubusercontent.com/544380/113608996-3c99e700-9619-11eb-97cd-9b7eb01e29f7.mov

When the app attempts to set the custom icon, it fails with an error, which is suppressed by a fire and forget effect

```
Error Domain=NSCocoaErrorDomain Code=4 "The file doesn’t exist." UserInfo={_LSLine=191, NSUnderlyingError=0x6000031a8210 {Error Domain=LSApplicationWorkspaceErrorDomain Code=-105 "iconName not found in CFBundleAlternateIcons entry" UserInfo={_LSLine=179, NSLocalizedDescription=iconName not found in CFBundleAlternateIcons entry, _LSFunction=-[LSAltIconManager _setAlternateIconName:forIdentifier:withIconsDictionary:error:]}}, _LSFunction=-[LSAltIconManager _setAlternateIconName:forIdentifier:withIconsDictionary:error:]}
```

I'll submit a PR to update info.plist to register the custom icons for iPad specifically.

**Comment by stephencelis** [comment]
Closed by #79. Thanks so much!
