### ISSUE TITLE
[Feature] - Time limit for multiplayer mode

### ISSUE THREAD

**Issue by jevonmao** [pointfreeco/isowords#88]
As described in the title, I think it will be a good feature if we add a time limit for each turn in multiplayer mode. For example, there can be an adjustable time limit of say 1 minute before the person's turn is forfeited. 

I will add more design details because I would actually like to work on this, once I get a better understanding of the codebase (just discovered this amazing project today).

**Comment by stephencelis** [comment]
@jevonmao We like to keep the issues section focussed on bugs (we should probably set up an issue template that communicates this). Cool if I convert this to a discussion instead?

**Comment by jevonmao** [comment]
Sureee

**Comment by stephencelis** [comment]
Thanks 😄 It's definitely a fun idea we've discussed in the past! Just haven't gotten around to trying to implement it.
